# Generated by Django 5.0.4 on 2024-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher')], default=1),
        ),
    ]
