# Generated by Django 5.0.4 on 2024-04-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default=None, upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default=None, upload_to='user/profile'),
        ),
    ]
