# Generated by Django 5.0.6 on 2024-06-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_stuclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Status',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], default='Student', max_length=20),
        ),
    ]
