# Generated by Django 5.0.6 on 2024-07-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='user/blank.jpg', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='user/blank.jpg', upload_to='user/profile'),
        ),
    ]
