# Generated by Django 5.0.4 on 2024-04-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_bannerimg_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='user/banner/obzpegdns0ng303sw6ag', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='user/profile/al1ig0r3ls3yalmtigio', upload_to='user/profile'),
        ),
    ]
