# Generated by Django 4.2.2 on 2023-10-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserId',
            field=models.CharField(default='aditya-7443-13@mpsajmer.com', max_length=5000),
        ),
    ]
