# Generated by Django 5.0.4 on 2024-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_bannerimg_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='user/gq6vctp5qvfav3ovxf8k', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='user/gq6vctp5qvfav3ovxf8k', upload_to='user/profile'),
        ),
    ]
