# Generated by Django 5.0.4 on 2024-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_bannerimg_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='https://res.cloudinary.com/dqvuoldfp/image/upload/v1714271769/media/user/gq6vctp5qvfav3ovxf8k.webp', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='https://res.cloudinary.com/dqvuoldfp/image/upload/v1714271769/media/user/gq6vctp5qvfav3ovxf8k.webp', upload_to='user/profile'),
        ),
    ]
