# Generated by Django 5.0.4 on 2024-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_bannerimg_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='static//blank.webp', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='static//blank.webp', upload_to='user/profile'),
        ),
    ]
