# Generated by Django 5.1 on 2024-12-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Status',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff'), ('Management', 'Management')], default='Student', max_length=20),
        ),
    ]
