# Generated by Django 4.2.4 on 2023-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bannerImg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/profile'),
        ),
    ]
