# Generated by Django 5.0 on 2024-01-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_bannerimg_alter_customuser_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='teacherStatusChoice',
            new_name='StatusChoice',
        ),
    ]
