# Generated by Django 5.0 on 2024-01-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_teacherstatuschoice_customuser_statuschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='StatusChoice',
            field=models.IntegerField(choices=[(1, 'Temporary'), (2, 'Probation'), (3, 'Permanent'), (4, 'Student'), (5, 'Teacher')], default=4),
        ),
    ]
