# Generated by Django 5.0 on 2024-01-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_statuschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='StatusChoice',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher')], default=4),
        ),
    ]
