# Generated by Django 5.0.1 on 2024-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_statuschoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='Hey There...!'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default='', null=True, upload_to='user/profile'),
        ),
    ]
