# Generated by Django 5.0.1 on 2024-01-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_bannerimg_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_management',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(blank=True, default='blank.webp', null=True, upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, default='blank.webp', null=True, upload_to='user/profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='schoolarNo',
            field=models.IntegerField(null=True),
        ),
    ]
