# Generated by Django 5.0.1 on 2024-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_is_management_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='schoolarNo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='schoolarNo_TIDNO',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
