# Generated by Django 5.0.1 on 2024-01-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_customuser_schoolarno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bannerImg',
            field=models.FileField(default='user/banner/blank.png', upload_to='user/banner'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.FileField(default='user/profile/blank.png', upload_to='user/profile'),
        ),
    ]
