# Generated by Django 5.0.1 on 2024-01-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='StatusChoice',
            new_name='Status',
        ),
    ]
