# Generated by Django 4.2.4 on 2023-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='navTarget',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
