# Generated by Django 4.2.4 on 2023-11-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_navigation_navtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='navTarget',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.navigation'),
        ),
    ]
