# Generated by Django 4.2.4 on 2023-11-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_navigation_navtarget_alter_navigation_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.navigation'),
        ),
    ]
