# Generated by Django 4.2.4 on 2023-11-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_navigation_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationAssist',
            fields=[
                ('navSno', models.AutoField(primary_key=True, serialize=False)),
                ('navName', models.CharField(max_length=100)),
                ('navTarget', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMain',
            fields=[
                ('navSno', models.AutoField(primary_key=True, serialize=False)),
                ('navName', models.CharField(max_length=50)),
                ('navTarget', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.AddField(
            model_name='navigationassist',
            name='navParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navigationmain'),
        ),
    ]
