# Generated by Django 4.2.4 on 2023-11-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_navigationassist_navigationmain_delete_navigation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationAssist',
        ),
        migrations.DeleteModel(
            name='NavigationMain',
        ),
    ]
