# Generated by Django 5.0.4 on 2024-04-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('snoPost', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('tagline', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, max_length=10000, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(default='', upload_to='blog/images')),
                ('allowed', models.BooleanField(default=False)),
                ('by_admin', models.BooleanField(default=False)),
                ('allowd_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
