# Generated by Django 4.2.4 on 2023-10-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('content', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, default='', max_length=600000, unique=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='static/blog/related_img/')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
