# Generated by Django 5.0.4 on 2024-05-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categories_alter_post_slug_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
