# Generated by Django 4.2.4 on 2023-10-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sno',
            new_name='snoPost',
        ),
    ]
