# Generated by Django 4.2.2 on 2023-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_sno_post_snopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
