# Generated by Django 5.0.1 on 2024-01-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
    ]
