# Generated by Django 5.0.1 on 2024-01-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
