# Generated by Django 5.0.4 on 2024-04-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookSno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=500)),
                ('bookName', models.CharField(default='', max_length=800)),
                ('numberOfChapters', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=800)),
                ('desc', models.CharField(default='', max_length=800)),
                ('bookCover', models.ImageField(default='', upload_to='elibrary/books/cover')),
                ('bookPDF', models.FileField(upload_to='elibrary/books/PDF')),
            ],
        ),
    ]
