# Generated by Django 4.2.4 on 2023-11-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookSno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=500)),
                ('bookPDF', models.FileField(upload_to='elibrary/books/PDF')),
            ],
        ),
    ]
