# Generated by Django 4.2.4 on 2023-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookName',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='book',
            name='numberOfChapters',
            field=models.IntegerField(default=0),
        ),
    ]
