# Generated by Django 4.2.4 on 2023-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0002_book_bookname_book_numberofchapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pubDate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
