# Generated by Django 5.0.4 on 2024-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0002_bookcategory_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
