# Generated by Django 5.0.6 on 2024-06-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0003_alter_bookcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='book',
            name='numberOfChapters',
        ),
    ]
