# Generated by Django 4.2.4 on 2023-11-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0003_book_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pubDate',
        ),
    ]
