# Generated by Django 4.2.4 on 2023-11-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0004_remove_book_pubdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
