# Generated by Django 4.2.4 on 2023-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Elibrary', '0005_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookSno', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=500)),
                ('bookName', models.CharField(default='', max_length=800)),
                ('numberOfChapters', models.IntegerField(default=0)),
                ('bookPDF', models.FileField(upload_to='elibrary/books/PDF')),
            ],
        ),
    ]
