# Generated by Django 4.2.4 on 2023-11-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookCover',
            field=models.ImageField(default='', upload_to='elibrary/books/cover'),
        ),
    ]
