# Generated by Django 4.2.4 on 2023-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0007_book_bookcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='', max_length=800),
        ),
    ]
