# Generated by Django 4.2.4 on 2023-12-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0008_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='', max_length=800),
        ),
    ]
